export default {
    AWARD: require('../assets/images/logo.png'),
    GOOGLE_ICON:require('../assets/images/ic_google.png'),
    FACEBOOK_ICON: require('../assets/images/ic_facebook.png'),
    APPLE_ICON:require('../assets/images/ic_apple.png'),
    BACK_ARROW:require('../assets/images/ic_back_arrow.png'),
    ic_down:require('../assets/images/ic_down.png'),
    tutorialpic: require('../assets/images/tutorial.png'),
    search_icon: require('../assets/images/ic_srch.png'),
    home_icon : require('../assets/images/ic_home.png'),
    profile_icon : require('../assets/images/ic_user.png'),
    notification_icon : require('../assets/images/ic_notify.png'),
    add_icon:require('../assets/images/ic_add.png'),
    icAPP: require('../assets/images/ic_home_icon.png'),
    icLOC: require('../assets/images/ic_loc.png'),
    icSHARE: require('../assets/images/ic_direction.png'),
    ic_logout:require ('../assets/images/ic_logout.png'),
    ic_key: require ('../assets/images/ic_key.png'),
    card_image:'https://images.unsplash.com/photo-1604049928882-31200d4a13cf?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80',
    profile_image: 'https://www.whatsappimages.in/wp-content/uploads/2021/12/Free-Stylish-Boys-Whatsapp-DP-Wallpaper-for-Status.jpg',   

}