export default {
    SLIDER:'Slider',
    LOGIN:'Login',
    PHONE_LOGIN:'Phone Login',
    NEW_ACCOUNT:'NewAccount',
    SET_PASSWORD:'Set Password',
    OTP_SCREEN:' Otp Screen',
    HOME: 'Home',
    PROFILE:'Profile',
    SEARCH_SCREEN:'Search screen',
    NOTIFICATIONS:'Notifications',
    ADD_SCREEN:'Add Screen',
    TAB_STACK:'Tab stack',
    EDIT_PROFILE_SCREEN:'Edit profile screen',
    CHANGE_PASSWORD:'Change Password',
    POST_ADD_SCREEN:'Post Add Screen',
    POST_DETAIL:'Post Detail',
    ADD_INFO :'Add Info',
    CHANGE_SCREEN:'changescreen'
}